apiVersion: v2
# image: "vectorim/element-web"
appVersion: v1.11.70
description: Communicate the way you want with Riot - a universal secure chat
  app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.30.0
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update matrixdotorg/synapse docker tag to v1.109.0 ([#74](https://github.com/halkeye/helm-charts/issues/74)) ([b9ad9c4](https://github.com/halkeye/helm-charts/commit/b9ad9c469ff34f7107eb07d26e32d44127cfffed))"
     - "**deps:** update matrixdotorg/synapse docker tag to v1.110.0 ([#75](https://github.com/halkeye/helm-charts/issues/75)) ([2c02ca8](https://github.com/halkeye/helm-charts/commit/2c02ca842ea7d5b43e4af385cc1382871c5914e2))"
     - "**deps:** update vectorim/element-web docker tag to v1.11.69 ([#73](https://github.com/halkeye/helm-charts/issues/73)) ([5976789](https://github.com/halkeye/helm-charts/commit/59767892787f195942503724bac0f7909e8ed3e2))"
     - "**deps:** update vectorim/element-web docker tag to v1.11.70 ([#76](https://github.com/halkeye/helm-charts/issues/76)) ([32bc923](https://github.com/halkeye/helm-charts/commit/32bc923862dd760b015d1f12fab34c6eff0bddb3))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: element-web
      image: "vectorim/element-web:v1.11.70"
